###
# GET Request to Access an Admin Resource
###

GET http://localhost:3000/api/auth/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imt3ODciLCJyb2xlcyI6WyJ1c2VyIiwiYWRtaW4iLCJldGMiXSwiYXVkIjoibm9kZVRlbXBsYXRlIiwiaXNzIjoicmVnaXN0ZXIiLCJuYmYiOjE3MTA3ODU4NzIsImp0aSI6IjQ0YTYzNGZkLTg5YTgtNGRhNy05ZDU3LWRkMGIzZDdhYTJhYyIsImlhdCI6MTcxMDc4NTg3MiwiZXhwIjoxNzEwNzg5NDcyfQ.cF_9C0ovMusWm7P18MyEL5RBXC7_uOQOQz476W2YLdk