###
# POST Request to Reset Password
###

POST http://localhost:3000/api/auth/password/reset
Content-Type: application/json

{
  "resetToken": "$2b$10$mBK/TKEuvd69lVmBm.F.oePigSpP6j3nmUvRFLZ7hTh8MOBIQvME2",
  "newPassword": "password2",
  "confirmPassword": "password2"
}