###
# POST Request to Create a New User
###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "kw87",
  "password": "password",
  "password2": "password",
  "email": "kw7@example.com",
  "roles": ["user","admin","etc"]
}