###
# GET Request to Access an Admin Resource
###

GET http://localhost:3000/api/auth/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwicm9sZXMiOlsiYWRtaW4iXSwiYXVkIjoibVBlcnNvbmEtbm9kZSIsImlzcyI6ImxvZ2luIiwibmJmIjoxNzA5Mjk5MjE1LCJqdGkiOiJhZTJkOWJlMC1iNDYzLTRjZGQtOWZlZi03NmY1MTZlNWRhMTQiLCJpYXQiOjE3MDkyOTkyMTUsImV4cCI6MTcwOTMwMjgxNX0.TknmI0Shgi8QAr2Rd_yA_RZwsbXE0z9rAB8tB0q1VeU