###
# DELETE Request to Delete User
###

DELETE http://localhost:3000/api/admin/users/662a5db8d94c6f6d0d61edf6e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MmE1YjhkOTRjNmY2ZDBkNjFlZGY2ZSIsInVzZXJuYW1lIjoidGVzdDQ1Iiwicm9sZXMiOlsidXNlciIsImV0YyIsImFkbWluIl0sImVtYWlsIjoia3d0ZXN0ZHNmYTcyZGRAZXhhbXBsZS5jb20iLCJhdWQiOiJub2RlVGVtcGxhdGUiLCJpc3MiOiJsb2dpbiIsIm5iZiI6MTcxNDA2MjQyMSwianRpIjoiNTg1ODM0OTQtOWY4NS00ZTQyLWJjZTgtMDQ3ZDE3M2M3NGFkIiwiaWF0IjoxNzE0MDYyNDIxLCJleHAiOjE3MTQwNjYwMjF9.oCr-31AjQzRLWOwF8GkHq5SyUOG2s22wfa7raQJM534
