###
# GET Request to Get User by Username or Email
###

GET http://localhost:3000/api/admin/users/kcwright@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imt3OTAiLCJyb2xlcyI6WyJ1c2VyIiwiYWRtaW4iLCJldGMiXSwiYXVkIjoibm9kZVRlbXBsYXRlIiwiaXNzIjoibG9naW4iLCJuYmYiOjE3MTA4NzY2NjQsImp0aSI6IjY0NWQ2N2ZiLTJlZmMtNDFlMC1iMmM1LWI3NmI0YzM4NDJkYiIsImlhdCI6MTcxMDg3NjY2NCwiZXhwIjoxNzEwODgwMjY0fQ.X3pijQS4BESiLsmr-43C9VHhKPqjyyQuVx1Twlw_dvo