###
# GET Request to Get User by ID
###

GET http://localhost:3000/api/admin/users/65fb0b9a00e296ca96149655
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imt3OTAiLCJyb2xlcyI6WyJ1c2VyIiwiYWRtaW4iLCJldGMiXSwiYXVkIjoibm9kZVRlbXBsYXRlIiwiaXNzIjoibG9naW4iLCJuYmYiOjE3MTEwNDA1NTgsImp0aSI6ImEzOTQ1ZDk0LWY0YmMtNDc0Mi04Yzc0LTY4ZTEyM2NlZWRjZSIsImlhdCI6MTcxMTA0MDU1OCwiZXhwIjoxNzExMDQ0MTU4fQ.14bMfCPyUJOUVzFuW-iEpTOCLlDQM0yK0ymn6o_pNkQ
